mavenJob("First-Maven-Project-Via-DSL") {
	description("First maven job generated by DSL on ${new Date()}")
	
	
	scm {
  		git {
   		 	remote {
   		  		 url 'https://github.com/amane12/project.git, master'
   		 	}
		}
	}
	

	triggers {
		scm('* * * * *')
	}

	rootPOM 'library1/pom.xml'
 	goals 'clean package'

	publishers {
		archiveArtifacts '**/*.war'
	}
}
