job("First-Maven-Project-Via-DSL"){
	description("First maven job generated by DSL on ${new Date()}")
	
	scm{
	properties {
		githubProjectUrl("https://github.com/amane12/project.git", master)
	}}

	triggers{
		scm('* * * * *')
	}

	steps{
		maven('clean package', 'pom.xml')
	}

	publishers{
		archiveArtifacts '**/*.war'
	}
}
